name: Flutter Build (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to build (staging, uat, preprod, prod)"
        required: true
        default: "uat"
        type: choice
        options:
          - staging
          - uat
          - preprod
          - prod
jobs:
  build:
    # âœ… This ensures the workflow only runs when you're on saad-dev-r5
    if: github.ref == 'refs/heads/saad-dev-r5'
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # use your Flutter version

      - name: ğŸ“¦ Get dependencies
        run: flutter pub get

      - name: ğŸ—ï¸ Build for selected platform and environment
        run: |
          ENVIRONMENT="${{ github.event.inputs.environment || 'uat' }}"
          
           echo "Building for platform: $PLATFORM and environment: $ENVIRONMENT"
          
            flutter build apk --release \
              --obfuscate \
              --split-debug-info=debug/$ENVIRONMENT  \
              --dart-define=ENV=$ENVIRONMENT 
